// let b = 2;

try{
    let a = 2 + b;
} catch(e) {
    console.log('O erro foi ' + e);
}

// Try Catch não para o código